
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znjrbzumhvaxlzwagwvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuanJienVtaHZheGx6d2Fnd3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNTQwNzAsImV4cCI6MjA1NjgzMDA3MH0.ZEO9n5xNjEhHLSEo-O6y4PS9WK4SGjN1n2k5X4KbaWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: typeof window !== 'undefined' ? localStorage : undefined
  }
});
